from google import genai
from google.genai import types
from app.core.config import settings

try:
    client = genai.Client(api_key=settings.GEMINI_API_KEY)
except Exception as e:
    client = None

def generate_proposal_stream(topic: str, requirements: str, retrieved_context: list[dict]):
    """Stream a proposal generated by Gemini Pro based on topic, requirements, and context."""
    if not client:
        raise Exception("Gemini client not initialized")
        
    context_text = "\n\n".join([f"[Source: {chunk.get('filename', 'Unknown')}]\n{chunk['text']}" for chunk in retrieved_context])
    
    system_instruction = """You are an expert Bid Manager and Proposal Writer for BidMindAI.
Your goal is to write a highly professional, persuasive, and comprehensive business proposal.
You must ground your proposal entirely in the provided retrieved context and align it with the user's specific requirements.
Structure it logically using standard industry sections:
1. Executive Summary
2. Proposed Solution
3. Methodology / Implementation Plan
4. Budget and Timeline
5. Conclusion

Be formal, detailed, and directly cite the provided sources when utilizing specific facts or capabilities."""

    prompt = f"""### Target Topic/RFP:
{topic}

### Specific Requirements:
{requirements}

### Retrieved Knowledge Base Context:
{context_text}

Please generate the comprehensive proposal now."""

    try:
        response_stream = client.models.generate_content_stream(
            model=settings.GEMINI_PRO_MODEL,
            contents=prompt,
            config=types.GenerateContentConfig(system_instruction=system_instruction)
        )
        
        for chunk in response_stream:
            if chunk.text:
                yield chunk.text
    except Exception as e:
        print(f"Error streaming proposal: {str(e)}")
        yield f"\n\n[Error generating proposal: {str(e)}]"
